const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'shirts',
      image: '/images/o1.webp',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReview: 10,
      description: 'high quality shirt',
    },
    {
      _id: '2',
      name: 'Umbro shirts',
      slug: 'Umbro-slim-shirt',
      category: 'shirts',
      image: '/images/o2.webp',
      price: 150,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.9,
      numReview: 30,
      description: 'high quality tutas',
    },
    {
      _id: '3',
      name: 'Adidas Fit Pants',
      slug: 'addidas-fit-pant',
      category: 'Pants',
      image: '/images/o3.webp',
      price: 110,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.7,
      numReview: 20,
      description: 'high quality pants',
    },

    {
      _id: '4',
      name: 'Armani Pants',
      slug: 'Armani-slim-pant',
      category: 'Pants',
      image: '/images/o4.webp',
      price: 90,
      countInStock: 0,
      brand: 'Armani',
      rating: 4.9,
      numReview: 20,
      description: 'High quality Pants',
    },
    {
      _id: '5',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'shirts',
      image: '/images/o1.webp',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '6',
      name: 'Umbro shirts',
      slug: 'Umbro-slim-shirt',
      category: 'shirts',
      image: '/images/o2.webp',
      price: 150,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.9,
      numReview: 30,
      description: 'high quality tutas',
    },
    {
      _id: '7',
      name: 'Adidas Fit Pants',
      slug: 'addidas-fit-pant',
      category: 'Pants',
      image: '/images/o3.webp',
      price: 110,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.7,
      numReview: 20,
      description: 'high quality pants',
    },

    {
      _id: '8',
      name: 'Armani Pants',
      slug: 'Armani-slim-pant',
      category: 'Pants',
      image: '/images/o4.webp',
      price: 90,
      countInStock: 0,
      brand: 'Armani',
      rating: 4.9,
      numReview: 20,
      description: 'High quality Pants',
    },
  ],
};

export default data;
