const data = {
  products: [
    {
      name: 'Balmain',
      slug: 'balmain-slin-shirt',
      category: 'shirts',
      image: '/images/r1.webp',
      price: 120,
      countInStock: 10,
      brand: 'Balmain',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Tiger of sweden',
      slug: 'slim tiger of sweden',
      category: 'shirts',
      image: '/images/r2.webp',
      price: 150,
      countInStock: 10,
      brand: 'Tiger of sweden',
      rating: 4.9,
      numReview: 30,
      description: 'high quality tutas',
    },
    {
      name: 'Prada shots',
      slug: 'prada shorts',
      category: 'Pants',
      image: '/images/e1.webp',
      price: 110,
      countInStock: 10,
      brand: 'Prada',
      rating: 4.7,
      numReview: 20,
      description: 'high quality pants',
    },

    {
      name: 'Armani Pants',
      slug: 'Armani-slim-pant',
      category: 'Pants',
      image: '/images/e2.webp',
      price: 90,
      countInStock: 0,
      brand: 'Armani',
      rating: 4.9,
      numReview: 20,
      description: 'High quality Pants',
    },
  ],
};

export default data;
